import Header from "@/components/Header";
import Head from "next/head";

const Search = () => {
  return ( 
    <>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/twitter.svg" />
      </Head>
      <Header label="Search" />
    </>
   );
}
 
export default Search;
